### ISSUE TITLE
Error: Can't find Python executable

### ISSUE THREAD

**Issue by themhz** [cirocosta/gulp-converter-tjs#18]
Hello, I am getting the following error when I attempt to npm install -g gulp-converter-tjs
It looks like I am missing python but the path is correct for python.exe . I can even run python command from my cmd and also enviroment variables are set. 
Any suggestions?

C:\Users\themhz\AppData\Roaming\npm\node_modules\gulp-converter-tjs\node_modules\iconv>if not defined npm_config_node_gy
p (node "C:\Users\themhz\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp
.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\themhz\AppData\Local\Programs\Python\Python36-32\python.exe
", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\themhz\AppData\Roaming\npm\node_modules\npm\node_modules\node-
gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\themhz\AppData\Roaming\npm\node_modules\npm\node_modules\node-g
yp\lib\configure.js:509:16)
gyp ERR! stack     at C:\Users\themhz\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\themhz\\AppData\\Roaming\\npm\\node_modules\\npm\\nod
e_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\themhz\AppData\Roaming\npm\node_modules\gulp-converter-tjs\node_modules\iconv
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iconv@2.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iconv@2.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\themhz\AppData\Roaming\npm-cache\_logs\2017-11-25T15_20_09_146Z-debug.log

**Comment by cosmo-naut** [comment]
Same error, very frustrating. Did you find a solution?

**Comment by mudasar** [comment]
Hi can you try installing node-gyp  
here are the instructions 
[https://github.com/nodejs/node-gyp#on-windows](url)
After installation you can run the npm i again and it'll start working

**Comment by cosmo-naut** [comment]
I solved this problem a day or two after my post, forgot to come back to it.

If I recall correctly the solution was found by installing some dependencies manually. If I'm not mistaken I believe node-gyp was one of them.
